name: Production

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Retrieve node version from .nvmrc
        run: echo "##[set-output name=NVMRC;]$(cat package.json | grep '\"node\":' | sed 's/^ *//;s/ *$//;s/\"node\":\ \"//;s/\",//')"
        id: nvm

      - name: Setup node ${{ steps.nvm.outputs.NVMRC }}
        uses: actions/setup-node@v1
        with:
          node-version: '${{ steps.nvm.outputs.NVMRC }}'

      - name: Install Dependencies
        run: yarn install

      - name: yarn build
        run: yarn build

      - name: Zip standalone build folder
        run: zip -r standalone_landing.zip public

      - name: 'Save standalone_landing.zip to artifacts'
        uses: actions/upload-artifact@v1
        with:
          name: 'standalone_landing'
          path: 'public'
